apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-amo-slack
  labels:
    release: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-5"
type: Opaque
data:
  crmLogin: {{  .Values.amo.crmLogin  | b64enc }}
  crmHash: {{ .Values.amo.crmHash | b64enc }}
  slackWebhook:  {{ .Values.amo.slackWebhook | b64enc }}
